version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db_docker
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./beauty-core-backend
      dockerfile: Dockerfile
    container_name: backend_api_docker
    restart: always
    depends_on:
      - db
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    networks:
      - app-network

volumes:
  mysql_data:
networks:
  app-network:
    driver: bridge
