spring.profiles.active=prod
spring.jpa.open-in-view=false

jwt.expiration=${JWT_EXPIRATION:900000000}
jwt.key=${JWT_KEY:NlWbWGB$pM08d-RSAD!hkR=JwbWIkzfHEEkx3=upOtrsHnJTrG#gZ-6RXb!qfQwpjbvmZTzl_Fkyx!$Hcre-Q#pPbnNmPrZSr#X2LvDrGyAECz&Z73xdtN4JlirAAre98_YGTIst5HweMqUsm8rWfLUD5sYOQtk=_u_oj_y9WmAqek3boIlz_fxNaJKJ3U117Fm=eSYgjQWSvR&ygGFLHB2T1sNjK7ITwlf&W02#osVpVojV&X9Fwmw4Y2EWZdWp2RwqTStog3dRCY$jtJgKciX5H4M91pOchWGgIJAizGGHJwe$#$la7PP_I-!eaShp_Iik#265M5h9vql_R4Y2Wg8#}

cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

# Specify the path of the Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true
