# MySQL Connection (Docker)
spring.datasource.url=jdbc:mysql://127.0.0.1:3308/beauty_core_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# Deixe o validate para garantir a estrutura
spring.jpa.hibernate.ddl-auto=validate

# Força a execução do script sempre
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:import.sql

# Logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true