package br.com.beautycore.api.controller;

import br.com.beautycore.api.dto.response.ProfessionalProfitGroupByDate;
import br.com.beautycore.api.dto.response.TotalProfitFiltered;
import br.com.beautycore.api.projections.TotalProfitInLiveProjection;
import br.com.beautycore.api.projections.TotalProfitProfessionalProjection;
import br.com.beautycore.api.services.FinancialReportService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.util.List;

@RestController
@RequestMapping("v1/financial-reports")
@RequiredArgsConstructor
@Tag(
name = "Financial Reports",
description = "Endpoints for retrieving financial reports, revenue summaries, and profit metrics."
)
public class FinancialReportController {

    private final FinancialReportService service;

    @Operation(
            summary = "Get total profit",
            description = "Returns the current total profit generated by all completed and paid appointments.",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Ok"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized")
            }
    )
    @SecurityRequirement(name = "bearerAuth")
    @PreAuthorize("isAuthenticated()")
    @GetMapping(value = "/profit", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<TotalProfitInLiveProjection> getTotalProfitInLive() {
        var result = service.getTotalProfitInLive();
        return ResponseEntity.ok(result);
    }

    @Operation(
            summary = "Get professional total profit",
            description = "Returns the current total profit generated by a specific professional.",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Ok"),
                    @ApiResponse(responseCode = "404", description = "Not found"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized"),
                    @ApiResponse(responseCode = "403", description = "Forbidden")
            }
    )
    @SecurityRequirement(name = "bearerAuth")
    @PreAuthorize("hasAnyRole('ADMIN', 'PROFESSIONAL')")
    @GetMapping(value = "/{professionalId}/profit", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<TotalProfitProfessionalProjection> getProfessionalTotalProfitInLive(@PathVariable Long professionalId) {
        var result = service.getProfessionalTotalProfitInLive(professionalId);
        return ResponseEntity.ok(result);
    }

    @Operation(
            summary = "Get total profit by period",
            description = "Returns the total profit calculated within a specified date range.",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Ok"),
                    @ApiResponse(responseCode = "400", description = "Bad request"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized")
            }
    )
    @SecurityRequirement(name = "bearerAuth")
    @PreAuthorize("isAuthenticated()")
    @GetMapping(value = "/summary", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<TotalProfitFiltered> getTotalProfitFiltered(@RequestParam(name = "start") String start, @RequestParam(name = "end") String end) {
        var result = service.getTotalProfitFiltered(start, end);
        return ResponseEntity.ok(result);
    }

    @Operation(
            summary = "Get total profit by period group by professional and date",
            description = "Returns the total professional profit calculated within a specified date range.",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Ok"),
                    @ApiResponse(responseCode = "400", description = "Bad request"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized")
            }
    )
    @SecurityRequirement(name = "bearerAuth")
    @PreAuthorize("isAuthenticated()")
    @GetMapping(value = "/professional-profits", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ProfessionalProfitGroupByDate>> findTotalProfitGroupedByProfessionalAndDate(@RequestParam(name = "start") String start, @RequestParam(name = "end") String end) {
        var result = service.findTotalProfitGroupedByProfessionalAndDate(start, end);
        return ResponseEntity.ok(result);
    }
}